[tool.pylint.main]
ignored-modules = "dependency_injector"
init-hook = "from pylint.config import find_default_config_files; import os, sys; sys.path.append(os.path.dirname('/src'))"

[tool.black]
line-length = 79

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 80
disable = """
    missing-module-docstring,
    missing-function-docstring
"""